# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HundredMillion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HundredMillion
	pod 'GoogleSignIn'
	pod 'GoogleAPIClientForREST/Drive'
	pod 'Charts'

end
